version: '3.8'
services:
  db:
    image: postgres
    restart: always
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "postgres", "-U", "root" ]
      timeout: 45s
      interval: 10s
      retries: 10
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: asset-mgmt
      # POSTGRES_EXTENSIONS: uuid-ossp
    volumes:
      - ./database/scripts:/docker-entrypoint-initdb.d
    ports:
      - 5432:5432